import Link from 'next/link'
import LoginBtn from './LoginBtn'
import './globals.css'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children}: {children: React.ReactNode}) {
  const session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar"> 
        <Link href="/" className="logo">홈</Link> 
        <Link href="/list">글목록</Link> 
        <LoginBtn/>
      </div>  
        {children}
      </body>
    </html>
  )
}
